
#include "my_header.h"

void init()
{	
	//enable clock on GPIOA and GPIOC
	SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOAEN);
	SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOCEN);
	
	//set PA[4-9] to output
	SET_BIT(GPIOA->MODER, GPIO_MODER_MODER4_0);	
	CLEAR_BIT(GPIOA->MODER, GPIO_MODER_MODER4_1);
	
	SET_BIT(GPIOA->MODER, GPIO_MODER_MODER5_0);	
	CLEAR_BIT(GPIOA->MODER, GPIO_MODER_MODER5_1);
	
	SET_BIT(GPIOA->MODER, GPIO_MODER_MODER6_0);	
	CLEAR_BIT(GPIOA->MODER, GPIO_MODER_MODER6_1);
	
	SET_BIT(GPIOA->MODER, GPIO_MODER_MODER7_0);	
	CLEAR_BIT(GPIOA->MODER, GPIO_MODER_MODER7_1);
	
	SET_BIT(GPIOA->MODER, GPIO_MODER_MODER8_0);	
	CLEAR_BIT(GPIOA->MODER, GPIO_MODER_MODER8_1);
	
	SET_BIT(GPIOA->MODER, GPIO_MODER_MODER9_0);	
	CLEAR_BIT(GPIOA->MODER, GPIO_MODER_MODER9_1);
	
	//set pull-up on PC13
	SET_BIT(GPIOC->PUPDR, GPIO_PUPDR_PUPD13_0);	
	CLEAR_BIT(GPIOC->PUPDR, GPIO_PUPDR_PUPD13_1);
	
}

void __delay(uint32_t i)
{
	while(i)
		--i;
}
